function [scenario] = HighwayStraight()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 30-Jun-2021 15:32:50

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    2000 0 0];
laneSpecifications = [lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)];
lsConnector = laneSpecConnector('TaperShape', 'None');
compLaneSpecification = compositeLaneSpec(laneSpecifications, 'Connector', lsConnector);
road(scenario, roadCenters, 'Lanes', compLaneSpecification, 'Name', 'Road');



