function [scenario] = HighwayCurved()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.10 (R2021a) and Automated Driving Toolbox 3.3 (R2021a).
% Generated on: 29-Jun-2021 10:57:32

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    150 0 0;
    300 -100 0;
    150 -200 0;
    0.4 -200 0];
laneSpecifications = [lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)
    lanespec(4, 'Width', 4)];
lsConnector = laneSpecConnector('TaperShape', 'None');
compLaneSpecification = compositeLaneSpec(laneSpecifications, 'Connector', lsConnector);
road(scenario, roadCenters, 'Lanes', compLaneSpecification, 'Name', 'Road');

